json.id task.id
json.name task.name
json.description task.description
json.projectId task.project_id
json.sectionId task.section_id
json.assigneeId task.assignee_id
json.dueOn task.due_on
json.completed task.completed
json.completedAt task.completed_at